### ISSUE TITLE
Bug: Comandos incorrectos

### ISSUE THREAD

**Issue by amunozdev** [apx-bot-team/apx-bot#9]
En el momento de ingresar un comando que no existe como por ejemplo, !bit o !bat, el programa devuelve error, crashea y se detiene.

![Captura de pantalla de 2021-11-06 17-56-13](https://user-images.githubusercontent.com/77214476/140623667-1207c44a-1d4c-4ab2-a878-85226808022c.png)

Para solucionar este problema, se podría hacer una condición if, que "pregunte" si el string ingresado es igual a algunos de los comandos disponibles. Si no es igual a ninguno, se podría devolver un mensaje, explicando que el comando ingresado es incorrecto y un comando (por ejemplo: !commands) para ver todos los comando disponibles.

**Comment by tobiasfacello** [comment]
**Solucionado**
El problema estaba en el reconocimiento de "alias" de cada comando:
![image](https://user-images.githubusercontent.com/69740939/140628883-e3ecc845-7dd5-4080-9d79-97ebf686fb52.png)
Borré el checkeo de **aliases**, por lo tanto habrá que hacer uso de _Slash Commands_ para que los usuarios puedan encontrar los comandos sin _tanto esfuerzo_ o sin tener que memorizar cada comando.

Cuando se ingrese un comando erróneo, devuelve lo siguiente:
![image](https://user-images.githubusercontent.com/69740939/140628916-20e0c9e1-4ea7-4f30-8946-13a0ab573a89.png)
